# Generated by Django 5.2.6 on 2025-09-29 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pertence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('estado', models.CharField(choices=[('em_posse', 'Em Posse'), ('levantado', 'Levantado')], default='em_posse', max_length=20)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('data_levantamento', models.DateTimeField(blank=True, null=True)),
                ('efetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pertences_pessoais', to='pessoas.efetivo')),
                ('entregue_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pertences_entregues', to='pessoas.efetivo')),
                ('levantado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pertences_levantados', to='pessoas.efetivo')),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pertences', to='visitas.visita')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoPertence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('entrega', 'Entrega'), ('levantamento', 'Levantamento')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_pertences', to='pessoas.efetivo')),
                ('pertence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='pertences.pertence')),
            ],
        ),
    ]
