# Generated by Django 5.2.6 on 2025-10-10 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_add_sigla_to_orgao'),
        ('pessoas', '0002_efetivo_usuario'),
        ('visitas', '0002_alter_visita_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSINotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=255, verbose_name='Nome da Pessoa')),
                ('data_visita', models.DateField(verbose_name='Data da Visita')),
                ('hora_visita', models.TimeField(verbose_name='Hora da Visita')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('urgencia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Urgência')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('visualizada', 'Visualizada'), ('processada', 'Processada')], default='pendente', max_length=15, verbose_name='Status')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsi_notifications', to='core.orgao', verbose_name='Órgão')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_processed', to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsi_notifications', to='visitas.visita', verbose_name='Visita')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsi_notifications', to='pessoas.visitante', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Notificação DSI',
                'verbose_name_plural': 'Notificações DSI',
                'ordering': ['-data_envio'],
                'indexes': [models.Index(fields=['status', 'data_envio'], name='notificatio_status_4cc105_idx'), models.Index(fields=['orgao', 'status'], name='notificatio_orgao_i_b91c22_idx'), models.Index(fields=['urgencia', 'status'], name='notificatio_urgenci_c91974_idx')],
            },
        ),
    ]
