# Generated by Django 5.2.6 on 2025-10-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_perfil_nivel_acesso'),
        ('usuarios', '0003_auto_20251001_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.perfil'),
        ),
    ]
