# Generated by Django 5.2.6 on 2025-09-29 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_realizados', to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.visitante')),
            ],
        ),
    ]
