# Generated by Django 5.2.6 on 2025-09-29 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, help_text='Número único da visita (gerado automaticamente).', max_length=25, null=True, unique=True)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('em_curso', 'Em Curso'), ('concluida', 'Concluída')], default='agendada', max_length=20)),
                ('data_hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('efetivo_visitar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_recebidas', to='pessoas.efetivo')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='core.orgao')),
                ('registado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registradas', to='pessoas.efetivo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='pessoas.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento_tipo', models.CharField(choices=[('BI', 'Bilhete de Identidade'), ('PASSAPORTE', 'Passaporte'), ('CARTA', 'Carta de Condução'), ('OUTRO', 'Outro')], max_length=20)),
                ('documento_numero', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(blank=True, max_length=100)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='visitas.visita')),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('cor', models.CharField(blank=True, max_length=30)),
                ('matricula', models.CharField(max_length=20)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaturas', to='visitas.visita')),
            ],
            options={
                'unique_together': {('matricula', 'visita')},
            },
        ),
    ]
