# Generated by Django 5.2.6 on 2025-10-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-data_registo']},
        ),
    ]
