# Generated by Django 5.2.6 on 2025-10-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_alter_visita_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.TextField(blank=True),
        ),
    ]
