# Generated by Django 5.2.6 on 2025-10-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_alter_visita_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='confirmada_recepcao',
            field=models.BooleanField(default=False, help_text='Recepção confirmou a passagem da visita por este órgão.'),
        ),
    ]
