# Generated by Django 5.2.6 on 2025-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
