# Generated by Django 5.2.6 on 2025-10-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orgao_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='sigla',
            field=models.CharField(blank=True, help_text='Sigla do órgão (ex: DG, RH)', max_length=20),
        ),
    ]
