# Generated by Django 5.2.6 on 2025-10-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_perfil_nivel_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('portaria', 'Portaria'), ('secretaria', 'Secretaria'), ('recepcao', 'Recepção'), ('suporte', 'Suporte Técnico')], default='portaria', max_length=20, verbose_name='nível de acesso'),
        ),
    ]
