# Generated by Django 5.2.6 on 2025-09-29 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cracha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('livre', 'Livre'), ('ocupado', 'Ocupado'), ('inativo', 'Inativo')], default='livre', max_length=20)),
                ('visita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cracha', to='visitas.visita')),
            ],
        ),
    ]
