# Generated by Django 5.2.6 on 2025-09-30 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crachas', '0001_initial'),
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cracha',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crachas', to='visitas.visita'),
        ),
    ]
