# Generated by Django 5.2.6 on 2025-09-29 12:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text="A chave única para identificar a configuração (ex: 'EMAIL_HOST').", max_length=100, unique=True)),
                ('valor', models.TextField(help_text='O valor da configuração, de acordo com o Tipo de Dado selecionado.')),
                ('tipo', models.CharField(choices=[('role', 'Role/Perfil'), ('permissao', 'Permissão'), ('instituicao', 'Nome da Instituição'), ('api', 'Configuração de API'), ('relatorio', 'Relatórios'), ('impressao', 'Impressão'), ('tema', 'Tema (Escuro/Claro)'), ('outro', 'Outro')], default='outro', help_text='O tipo de configuração para agrupamento e contexto de uso.', max_length=20)),
                ('tipo_dado', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Booleano (True/False)'), ('json', 'JSON')], default='texto', help_text='O tipo de dado do valor, para validação e conversão automática.', max_length=20)),
                ('descricao', models.CharField(blank=True, help_text='Uma breve descrição sobre o propósito desta configuração.', max_length=255)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a configuração está ativa e deve ser usada pelo sistema.')),
                ('sensivel', models.BooleanField(default=False, help_text='Marque se o valor for sensível (ex: senha, API key). O valor não será exibido em logs ou interfaces de forma clara.')),
                ('logotipo', models.ImageField(blank=True, help_text='Logotipo para relatórios e impressão, se aplicável.', null=True, upload_to='configuracoes/logotipos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['tipo', 'chave'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConfiguracaoSistema',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, help_text="A chave única para identificar a configuração (ex: 'EMAIL_HOST').", max_length=100)),
                ('valor', models.TextField(help_text='O valor da configuração, de acordo com o Tipo de Dado selecionado.')),
                ('tipo', models.CharField(choices=[('role', 'Role/Perfil'), ('permissao', 'Permissão'), ('instituicao', 'Nome da Instituição'), ('api', 'Configuração de API'), ('relatorio', 'Relatórios'), ('impressao', 'Impressão'), ('tema', 'Tema (Escuro/Claro)'), ('outro', 'Outro')], default='outro', help_text='O tipo de configuração para agrupamento e contexto de uso.', max_length=20)),
                ('tipo_dado', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Booleano (True/False)'), ('json', 'JSON')], default='texto', help_text='O tipo de dado do valor, para validação e conversão automática.', max_length=20)),
                ('descricao', models.CharField(blank=True, help_text='Uma breve descrição sobre o propósito desta configuração.', max_length=255)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a configuração está ativa e deve ser usada pelo sistema.')),
                ('sensivel', models.BooleanField(default=False, help_text='Marque se o valor for sensível (ex: senha, API key). O valor não será exibido em logs ou interfaces de forma clara.')),
                ('logotipo', models.TextField(blank=True, help_text='Logotipo para relatórios e impressão, se aplicável.', max_length=100, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Configuração do Sistema',
                'verbose_name_plural': 'historical Configurações do Sistema',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
