# Generated by Django 5.2.6 on 2025-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='manual_utilizador',
            field=models.FileField(blank=True, help_text='Manual do utilizador em formato PDF.', null=True, upload_to='configuracoes/manuais/'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaosistema',
            name='manual_utilizador',
            field=models.TextField(blank=True, help_text='Manual do utilizador em formato PDF.', max_length=100, null=True),
        ),
    ]
