# Generated by Django 5.2.6 on 2025-09-29 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Efetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('numero_funcional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efetivos', to='core.orgao')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_pessoa', models.CharField(choices=[('singular', 'Singular'), ('coletiva', 'Coletiva')], default='singular', max_length=10)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('designacao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_tipo', models.CharField(blank=True, choices=[('BI', 'Bilhete de Identidade'), ('PASSAPORTE', 'Passaporte'), ('CARTA', 'Carta de Condução'), ('OUTRO', 'Outro')], max_length=20, null=True)),
                ('documento_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_validade', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('nif', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='visitantes_fotos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representados', to='pessoas.visitante')),
            ],
        ),
    ]
