# Generated by Django 5.2.6 on 2025-10-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_efetivo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='documento_emissao',
            field=models.DateField(blank=True, help_text='Data de emissão do documento', null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='estado_civil',
            field=models.CharField(blank=True, help_text='Estado civil', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='provincia_nascimento',
            field=models.CharField(blank=True, help_text='Província de nascimento', max_length=100, null=True),
        ),
    ]
