# Generated by Django 5.2.6 on 2025-10-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_visitante_documento_emissao_visitante_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='documento_numero',
            field=models.CharField(blank=True, help_text='Número do documento de identificação (único)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nif',
            field=models.CharField(blank=True, help_text='Número de Identificação Fiscal (único)', max_length=20, null=True, unique=True),
        ),
    ]
