# Generated by Django 5.2.6 on 2025-09-29 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(blank=True, help_text='Data e hora em que o visitante entrou.', null=True)),
                ('data_saida', models.DateTimeField(blank=True, help_text='Data e hora em que o visitante saiu.', null=True)),
                ('registrado_por_entrada', models.ForeignKey(help_text='Utilizador que registrou a entrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrado_por_saida', models.ForeignKey(blank=True, help_text='Utilizador que registrou a saída.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visita', models.OneToOneField(help_text='A visita agendada para a qual este acesso está sendo registrado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acesso', to='visitas.visita')),
            ],
        ),
    ]
