# Generated by Django 5.2.6 on 2025-10-17 16:37

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('categoria', models.CharField(choices=[('geral', 'Geral'), ('tecnico', 'Problema Técnico'), ('usuario', 'Dúvida de Usuário'), ('sistema', 'Problema do Sistema'), ('seguranca', 'Segurança'), ('melhoria', 'Sugestão de Melhoria')], max_length=20, verbose_name='Categoria')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=10, verbose_name='Prioridade')),
                ('titulo_template', models.CharField(max_length=200, verbose_name='Título Template')),
                ('descricao_template', models.TextField(verbose_name='Descrição Template')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Template de Ticket',
                'verbose_name_plural': 'Templates de Tickets',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('numero', models.CharField(db_index=True, max_length=20, verbose_name='Número do Ticket')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('geral', 'Geral'), ('tecnico', 'Problema Técnico'), ('usuario', 'Dúvida de Usuário'), ('sistema', 'Problema do Sistema'), ('seguranca', 'Segurança'), ('melhoria', 'Sugestão de Melhoria')], default='geral', max_length=20, verbose_name='Categoria')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('aguardando_usuario', 'Aguardando Usuário'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Atualização')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('tempo_resolucao_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tempo de Resolução (horas)')),
                ('satisfacao_usuario', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Satisfação do Usuário (1-5)')),
                ('comentario_satisfacao', models.TextField(blank=True, null=True, verbose_name='Comentário sobre Satisfação')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atribuido_para', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído para')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'historical Ticket',
                'verbose_name_plural': 'historical Tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número do Ticket')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('geral', 'Geral'), ('tecnico', 'Problema Técnico'), ('usuario', 'Dúvida de Usuário'), ('sistema', 'Problema do Sistema'), ('seguranca', 'Segurança'), ('melhoria', 'Sugestão de Melhoria')], default='geral', max_length=20, verbose_name='Categoria')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('aguardando_usuario', 'Aguardando Usuário'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('tempo_resolucao_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tempo de Resolução (horas)')),
                ('satisfacao_usuario', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Satisfação do Usuário (1-5)')),
                ('comentario_satisfacao', models.TextField(blank=True, null=True, verbose_name='Comentário sobre Satisfação')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('atribuido_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído para')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTicketComment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Atualização')),
                ('interno', models.BooleanField(default=False, verbose_name='Comentário Interno')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'historical Comentário do Ticket',
                'verbose_name_plural': 'historical Comentários dos Tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='tickets/anexos/%Y/%m/%d/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('tamanho', models.BigIntegerField(verbose_name='Tamanho (bytes)')),
                ('tipo_mime', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tickets.ticket', verbose_name='Ticket')),
                ('upload_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Upload por')),
            ],
            options={
                'verbose_name': 'Anexo do Ticket',
                'verbose_name_plural': 'Anexos dos Tickets',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('interno', models.BooleanField(default=False, verbose_name='Comentário Interno')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Comentário do Ticket',
                'verbose_name_plural': 'Comentários dos Tickets',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridade'], name='tickets_tic_priorid_869197_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['categoria'], name='tickets_tic_categor_d8899a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['solicitante'], name='tickets_tic_solicit_0ca894_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['atribuido_para'], name='tickets_tic_atribui_37833a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['data_criacao'], name='tickets_tic_data_cr_09e150_idx'),
        ),
    ]
